ALTER TABLE Drawn_By
ADD CONSTRAINT FK_Drawn_By_Artist FOREIGN KEY(ArtistID) REFERENCES Artist(ArtistID);

ALTER TABLE Drawn_By
ADD CONSTRAINT FK_Drawn_By_Issue FOREIGN KEY(IssueID) REFERENCES Issue(IssueID);

ALTER TABLE Member_Of
ADD CONSTRAINT FK_Member_Of_Superhero FOREIGN KEY(SuperheroID) REFERENCES Superhero(SuperheroID) ON DELETE CASCADE;

ALTER TABLE Member_Of
ADD CONSTRAINT FK_Member_Of_Team FOREIGN KEY(TeamID) REFERENCES Team(TeamID) ON DELETE CASCADE;

ALTER TABLE Adapted_To
ADD CONSTRAINT FK_Adapted_To_Superhero FOREIGN KEY(SuperheroID) REFERENCES Superhero(SuperheroID) ON DELETE CASCADE;

ALTER TABLE Adapted_To
ADD CONSTRAINT FK_Adapted_To_Movie_Adaptation FOREIGN KEY(MovieID) REFERENCES Movie_Adaptation(MovieID) ON DELETE CASCADE;

ALTER TABLE Mentored_By
ADD CONSTRAINT FK_Mentored_By_Superhero FOREIGN KEY(SuperheroID) REFERENCES Superhero(SuperheroID) ON DELETE CASCADE;

ALTER TABLE Mentored_By
ADD CONSTRAINT FK_Mentored_By_Sidekick FOREIGN KEY(SidekickID) REFERENCES Sidekick(SidekickID);

ALTER TABLE Plays_In
ADD CONSTRAINT FK_Plays_In_Movie_Adaptation FOREIGN KEY(MovieID) REFERENCES Movie_Adaptation(MovieID) ON DELETE CASCADE;

ALTER TABLE Plays_In
ADD CONSTRAINT FK_Plays_In_Actor FOREIGN KEY(ActorID) REFERENCES Actor(ActorID);
